[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/badge/*"
  to = "https://api.nickword.com/badge/:splat"
  status = 200

# Rule for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # force = true

[[headers]]
  for = "/static/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/static/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/favicon-16x16.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/favicon-32x32.png"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
